#!/usr/bin/env python3
"""Build blog posts from Markdown to HTML."""

import re
import sys
from datetime import datetime
from pathlib import Path

try:
    import markdown
    import yaml
except ImportError:
    print("Missing dependencies. Install with: pip install markdown pyyaml")
    sys.exit(1)

CONTENT_DIR = Path("content/posts")
OUTPUT_DIR = Path("posts")

TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - David Rein</title>
    <link rel="stylesheet" href="../styles.css">
    <link rel="apple-touch-icon" sizes="180x180" href="../files/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../files/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../files/favicon/favicon-16x16.png">
    <link rel="manifest" href="../files/favicon/site.webmanifest">
    <meta name="description" content="{description}">
</head>
<body>
    <div class="page">
        <nav class="post-nav">
            <a href="/">&larr; David Rein</a>
        </nav>

        <article class="post">
            <header class="post-header">
                <h1>{title}</h1>
                <time class="post-date" datetime="{date_iso}">{date_display}</time>
            </header>

            <div class="post-body">
                {body}
            </div>
        </article>
    </div>
    <script src="../footnotes.js"></script>
</body>
</html>
"""


def parse_frontmatter(text):
    """Parse YAML frontmatter from markdown text."""
    if not text.startswith("---"):
        raise ValueError("No frontmatter found")
    end = text.index("---", 3)
    meta = yaml.safe_load(text[3:end])
    body = text[end + 3 :].strip()
    return meta, body


def process_footnotes(html):
    """Convert bottom-of-page footnotes into inline popup spans."""
    # Find the footnote section generated by python-markdown
    fn_match = re.search(
        r'<div class="footnote">\s*<hr\s*/?>\s*<ol>(.*?)</ol>\s*</div>',
        html,
        re.DOTALL,
    )
    if not fn_match:
        return html

    # Extract each footnote's content
    footnotes = {}
    for li in re.finditer(
        r'<li id="fn:(.+?)">\s*(.*?)\s*</li>', fn_match.group(1), re.DOTALL
    ):
        fn_id = li.group(1)
        content = li.group(2)
        # Remove the backref link and its preceding non-breaking space
        content = re.sub(
            r"\s*&#160;\s*<a [^>]*class=\"footnote-backref\"[^>]*>.*?</a>",
            "",
            content,
        )
        content = content.strip()
        # Unwrap single-paragraph footnotes
        if content.startswith("<p>") and content.endswith("</p>") and content.count("<p>") == 1:
            content = content[3:-4].strip()
        footnotes[fn_id] = content

    # Remove the footnote section
    html = html[: fn_match.start()] + html[fn_match.end() :]

    # Replace each reference with a popup span
    def replace_ref(m):
        fn_id = m.group(1)
        num = m.group(2)
        content = footnotes.get(fn_id, "")
        return (
            f'<span class="footnote-ref" tabindex="0" role="button" '
            f'aria-label="Footnote {num}">'
            f"<sup>{num}</sup>"
            f'<span class="footnote-popup" role="tooltip">{content}</span>'
            f"</span>"
        )

    # fnref\d* handles repeated references (fnref2:, fnref3:, etc.)
    html = re.sub(
        r'<sup id="fnref\d*:(.+?)"><a class="footnote-ref" href="#fn:.+?">(\d+)</a></sup>',
        replace_ref,
        html,
    )

    return html


def build_post(md_path):
    """Convert a single markdown file to HTML."""
    text = md_path.read_text()
    meta, body_md = parse_frontmatter(text)

    md = markdown.Markdown(extensions=["footnotes", "smarty"])
    body_html = md.convert(body_md)
    body_html = process_footnotes(body_html)

    date = meta["date"]
    if isinstance(date, str):
        date = datetime.strptime(date, "%Y-%m-%d")
    date_iso = date.strftime("%Y-%m-%d")
    date_display = f"{date.strftime('%B')} {date.day}, {date.year}"

    slug = meta.get("slug", md_path.stem)
    out_path = OUTPUT_DIR / f"{slug}.html"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        TEMPLATE.format(
            title=meta["title"],
            description=meta.get("description", ""),
            date_iso=date_iso,
            date_display=date_display,
            body=body_html,
        )
    )
    print(f"  {md_path} -> {out_path}")


def main():
    if not CONTENT_DIR.exists():
        print(f"No content directory at {CONTENT_DIR}")
        sys.exit(1)

    posts = sorted(CONTENT_DIR.glob("*.md"))
    if not posts:
        print("No markdown files found.")
        return

    print(f"Building {len(posts)} post(s)...")
    for p in posts:
        build_post(p)
    print("Done.")


if __name__ == "__main__":
    main()
